version: '3.4'

services:
  chat.chatwebbrowser:
    image: ${DOCKER_REGISTRY-}chatchatwebbrowser
    build:
      context: .
      dockerfile: Chat.ChatWebBrowser/Dockerfile

  chat.webapi:
    image: ${DOCKER_REGISTRY-}chatwebapi
    build:
      context: .
      dockerfile: Chat.WebApi/Dockerfile
    ports:
     - "50950:80"      
    depends_on:
        - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
     - "SA_PASSWORD=Your_password123"
     - "ACCEPT_EULA=Y"
